### ISSUE TITLE
Does BBG support generating C32 documents? 

### ISSUE THREAD

**Issue by jonbartels** [amida-tech/blue-button-generate#28]
Does BBG support generating C32 documents?

If yes - What generation options should I use to get a C32?

If no - Is there documentation that would get me started on generating a C32 template?

**Comment by jonbartels** [comment]
I hope this example helps clarify my question.

I attempted this from a clone of the blue-button project.

```
//template IDs are 2.16.840.1.113883.10.20.22.1.1 and 2.16.840.1.113883.10.20.22.1.2
var data = "a CCDA as a string, omitted here for brevity"
//read a CCD
console.log("parsing statically coded dummy CCDA");
var inputCCD = parser.parse(data);

console.log("got input ccd as: " + typeof inputCCD);

//??? magic happens??

//write a C32
var bbg = require("blue-button-generate");
console.log("imported bbg as: " + typeof bbg);
console.log("calling generateCCD");
//this call errors
var c32 = bbg.generateCCD(inputCCD, { type: "c32"});

console.log("got c32");
console.log(c32);
```

This errored with:
`blue-button/node_modules/blue-button-generate/lib/headerLevel.js:24
                    return input.substring(0, 1);`

I made local changes to headerLevel.js, I changed `input` to `input.code` to get past this error. Input is a code object at this point.

I got output that started with:
```<?xml version="1.0" encoding="UTF-8"?>
<ClinicalDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:hl7-org:v3" xmlns:cda="urn:hl7-org:v3" xmlns:sdtc="urn:hl7-org:sdtc">
  <realmCode code="US"/>
  <typeId root="2.16.840.1.113883.1.3" extension="POCD_HD000040"/>
  <templateId root="2.16.840.1.113883.10.20.22.1.1"/>
  <templateId root="2.16.840.1.113883.10.20.22.1.2"/>```

I suspect that I am either not calling generateCCD correctly to get a C32 or that C32 generation isn't supported.

**Comment by au2** [comment]
BBG only generates CCDA; C32 is not supported.

**Comment by jonbartels** [comment]
I think I have found my own answer. 

documentLevel.js defines the template IDs and other rendering rules. There is only a definition for ccd and ccd2. Those appear to be CCDA 1.1 and 2.1. Those document definitions in turn make use of sectionLevel and sectionLevel2.

So no there is no C32 rendering supported at this time. 

If I needed C32 support I'd have to extend documentLevel and implement a C32 document and supporting sections. I may be able to re-use compatible pieces from CCDA 1.1 and 1.2 though.
