### ISSUE TITLE
Errors Installing from NodeJS

### ISSUE THREAD

**Issue by joshmc82** [amida-tech/blue-button-generate#32]
When trying to execute the npm install, it returns errors with required dependencies:

This is an abbreviated stack trace, but I believe it shows the main culprit. 
`npm ERR! code 1
npm ERR! path /Users/josh/node_modules/libxmljs
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build --loglevel http
npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/Users/josh/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/Users/josh/node_modules/libxmljs/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.19.10/node-v93-darwin-arm64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/libxmljs/libxmljs/releases/download/v0.19.10/node-v93-darwin-arm64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for libxmljs@0.19.10 and node@16.15.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/libxmljs/libxmljs/releases/download/v0.19.10/node-v93-darwin-arm64.tar.gz`

**Comment by Manhydra** [comment]
This is due to a compilation issue with libxmljs@0.19.10

https://github.com/amida-tech/blue-button/issues/260

**Comment by sjpadgett** [comment]
There are pre compiled libxmljs for both windows and Linux available.
