### ISSUE TITLE
Sample Code Question

### ISSUE THREAD

**Issue by joshmc82** [amida-tech/blue-button-generate#33]
In your sample code, you appear to be reading a CCDA XML file, converting to JSON, leaving room for manipulation via JSON, then outputting the updated XML file again at the end.
For my use case, I'd like to take a JSON formatted string in the blue-button model (i.e. https://github.com/amida-tech/blue-button/blob/master/example/example3.json) and generate a CCDA XML back.
When I use the below code, I get back only an empty CCDA "shell". What am I doing wrong? No errors are shown on the console.

`// Require express and create an instance of it
const express = require('express');
const bodyParser = require('body-parser');
const app = express();
const xmlTextParser = bodyParser.text({limit: '10mb', type:'application/xml'});
const jsonParser = bodyParser.text({limit: '10mb', type:'application/json'});
const bb = require('@amida-tech/blue-button');
const bbg = require('@amida-tech/blue-button-generate');

//handle post on /xml2json
app.post('/xml2json', xmlTextParser, function (req, res) {
    var outputJSON = bb.parseXML(req.body);
    res.type('json');
    res.send(JSON.stringify(outputJSON));
});

//handle post on /json2xml
app.post('/json2xml', jsonParser, function (req, res) {
    res.type('xml');
    var updatedXMLString = bbg.generateCCD(req.body);
    
    res.send(updatedXMLString);
});

// Change the 404 message modifing the middleware
app.use(function(req, res, next) {
    res.status(404).send("Sorry, that route doesn't exist. Have a nice day :)");
});

// start the server in the port 9090 !
app.listen(9090, function () {
    console.log('Server listening on port 9090.');
});
`

**Comment by joshmc82** [comment]
Sorted out my own problem but posting here for reference in case someone else comes across this.

1. You have to parse the request body as JSON
2. You need to make sure you are sending a well formed JSON model. If your model is off, it can't read it and will send back just the generic XML.

**Comment by sjpadgett** [comment]
@joshmc82 I've been using this library for several years in our EMR. Though I've modified a considerable bit to get us up to Rel 2.1 and cures act, it may be helpful to see what I've done. We recently certified with ONC.

The nodejs app serveccda.js is where I deal with receiving an array from socket to build CCD/Referral etc.
I hope this will help you in some way.

https://github.com/openemr/openemr/tree/master/ccdaservice

**Comment by sjpadgett** [comment]
Here's a resulting document
![Summarization-of-Episode-Note](https://user-images.githubusercontent.com/1859985/182689505-2d259ab2-5738-43d7-a0fe-39f9ff96fcc0.png)

**Comment by joshmc82** [comment]
@sjpadgett wow, that is pretty impressive. I will definitely check this out. Much appreciated, friend.

**Comment by sjpadgett** [comment]
@joshmc82 Attached is a dump of the resulting object received from EMR socket transaction after parse. I send from EMR as a XML array then convert into json object that gets fed to generator engine. Also included the XML result from generator.

This will help you understand more clearly what the generator engine needs in my implementation.
My hope is this will help speed up your develop needs and save some nail biting that I went through.
Good luck and you're welcomed to grab whatever you need from my implementation. It'd be nice if you shared how you're using for mine and perhaps library authors curiosity.

[exampleccda.zip](https://github.com/amida-tech/blue-button-generate/files/9254522/exampleccda.zip)
